BEGIN TRANSACTION;
DROP TABLE IF EXISTS "metaData";
CREATE TABLE IF NOT EXISTS "metaData" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"currentTerm"	INTEGER NOT NULL,
	"votedFor"	INTEGER NOT NULL
);
DROP TABLE IF EXISTS "nodeLog";
CREATE TABLE IF NOT EXISTS "nodeLog" (
	"id"	INTEGER NOT NULL,
	"term"	INTEGER NOT NULL,
	"data"	BLOB NOT NULL,
	PRIMARY KEY("id")
);
COMMIT;